# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yAK9U9SHI0LnxxPZP5Cf8pWB_YZDeUhX
"""

nota = float(input("digite uma nota entre zero e dez"))
while nota > 10 or nota < 0:
  nota = float(input("digite um valor valido:"))
print("sucesso")

usuario =  int(input("insira o nome de usuario "))
senha = int(input("digite uma senha "))
while senha == usuario:
 print("ERRO")

numero = 1
while numero <= 10:
 print("o valor atual de numero é 5 ")
 numero += 1

numero = 2
while numero <= 20:
  print(f"o valor atual de numero é {numero} ")
  numero += 2

usuario = int(input("insira um numero "))
contador = 1
while contador <= usuario:
 print(f"valor atual do contador é {contador} ")
 contador += 1

usuario = int(input("insira um numero "))
contador = 2
while contador <= usuario:
 print(f"valor atual do contador é {contador} ")
 contador += 2

numero = int(input("digite um numero:"))
contador = 1
while contador <= 10:
  resultado = numero * contador
  print(f"{numero} x {contador} x {resultado}")
  contador += 1

senha = "rene2002"
usuario = input("insira uma senha ")
while senha != usuario:
 print("senha incorreta ")
 usuario = input("insira uma senha ")
 print("senha correta ")



soma = 0
usuario =  int(input("insira um numero inicial"))
while  usuario != 0:
 usuario = int(input("insira outro numero: "))
 soma += usuario
print(f"ao digitar 0 todos os numeros vao somar e o resultado é {soma}  ")

maiornumero = 0
usuario = int(input("insira um numero inicial "))
while usuario >= 0:

 usuario = int(input("insira outro numero "))
if usuario < 0:
while usuario >= maiornumero:

  maiornumero = usuario
print(f" o numero inserido o resultado é {maiornumero}  ")
 print("Numero negativo")